### ISSUE TITLE
Php error with footer.php in About and Team

### ISSUE THREAD

**Issue by JinxQc** [Hircinus/CRHS_Robotics-2020#18]
At the bottom of those pages I get errors messages from wampserver.

For about:
![image](https://user-images.githubusercontent.com/32917220/72122312-7a7f6100-332b-11ea-9182-9383491ddf5f.png)

For Team:
![image](https://user-images.githubusercontent.com/32917220/72122332-89661380-332b-11ea-8e76-d1e993ba7ecc.png)

Firefox dev edition

**Comment by Hircinus** [comment]
Are the URL's proper?

**Comment by JinxQc** [comment]
@Hircinus With a debugger I found out that the bug is at line 71 on footer.php with"$link = $links[$x];" on it's final pass of the links when variable x equals 8 it says undefined offset 7 I don't know how what the problem is maybe you do but I'll keep trying.

**Comment by Hircinus** [comment]
Please show me the file that you have so I can see and figure it out.

**Comment by JinxQc** [comment]
![image](https://user-images.githubusercontent.com/32917220/72213286-2f478880-34ba-11ea-9a0b-5143f806d7fb.png)
@Hircinus It's actually not because of what I said earlier. It's because it's trying to call on the 7th link in the array but there are only six items. (Footer.php Sidebar code)

**Comment by JinxQc** [comment]
Fixed issue by making it < count(links) 
since # of links will always be smaller than # of rows

![image](https://user-images.githubusercontent.com/32917220/72213469-8bf87280-34bd-11ea-8a9c-2fb118d28793.png)
